name: Love The Dance
favicon: null
layout_spectrum: 0.50002
typography_spectrum: 0.29556
title: Love The Dance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c53324'
    - '#fa9c35'
    - '#000000'
    - '#6fbe51'
    - '#018ad3'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
