name: Love The Dance
favicon: null
layout_spectrum: 0.97934
typography_spectrum: 0.844813430448994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c53324'
    - '#fa9c35'
    - '#000000'
    - '#6fbe51'
    - '#018ad3'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
